manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tangbonze
      url-base: https://github.com/tangbonze
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: manna-harbour
      url-base: https://github.com/manna-harbour
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: tangbonze
      revision: main
    - name: prospector-zmk-module
      remote: carrefinho
      revision: main
    - name: miryoku_zmk
      remote: manna-harbour
      revision: master
      path: miryoku
  self:
    path: config
